# Generated by Django 2.0.13 on 2019-05-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(help_text='xx/xx/xxxx', null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='000.000.000-00', help_text='Por favor, entre com um CPFseguindo o formato: XXX.XXX.XXX-XX', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(default='00', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do usuário'),
        ),
    ]
