# Generated by Django 2.0.13 on 2019-05-10 01:17

import dashboard.users.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190510_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='Por favor, entre com um CPFseguindo o formato: XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[dashboard.users.utils.validators.validate_cpf]),
        ),
    ]
