# Generated by Django 2.0.13 on 2019-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190510_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(help_text='DD/MM/AAAA', null=True, verbose_name='Birthday'),
        ),
    ]
