# Generated by Django 2.0.13 on 2019-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='identifier',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='notification',
            name='infraction_identifier',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
