# Generated by Django 2.0.13 on 2019-05-15 20:09

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radar',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='radar',
            name='longitude',
        ),
        migrations.AddField(
            model_name='radar',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
