# Generated by Django 2.0.13 on 2019-06-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_auto_20190515_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='identificacao',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Identificação do Radar'),
        ),
    ]
